DROP TABLE Triplos
DROP TABLE Posicao
DROP TABLE Contacto_Telefonico
DROP TABLE Contacto_Email
DROP TABLE Contacto
DROP TABLE Cliente
DROP TABLE Registo
DROP TABLE Instrumento_Financeiro
DROP TABLE Valores_Mercado
DROP TABLE Mercado_Financeiro