//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Si2_Fase2_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instrumento_Financeiro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Instrumento_Financeiro()
        {
            this.Posicao = new HashSet<Posicao>();
            this.Registo = new HashSet<Registo>();
        }
    
        public string ISIN { get; set; }
        public string CodigoMercado { get; set; }
        public string Descricao { get; set; }
        public Nullable<decimal> ValorAtual { get; set; }
        public Nullable<decimal> ValorVariacaoDiaria { get; set; }
        public Nullable<decimal> PercentagemVariacaoDiaria { get; set; }
        public Nullable<decimal> ValorVariacao6Meses { get; set; }
        public Nullable<decimal> PercentagemVariacao6Meses { get; set; }
        public Nullable<decimal> Media6Meses { get; set; }
    
        public virtual Mercado_Financeiro Mercado_Financeiro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Posicao> Posicao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registo> Registo { get; set; }
    }
}
