//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Si2_Fase2_EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PilimEntities : DbContext
    {
        public PilimEntities()
            : base("name=PilimEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Contacto> Contacto { get; set; }
        public virtual DbSet<Contacto_Email> Contacto_Email { get; set; }
        public virtual DbSet<Contacto_Telefonico> Contacto_Telefonico { get; set; }
        public virtual DbSet<Instrumento_Financeiro> Instrumento_Financeiro { get; set; }
        public virtual DbSet<Mercado_Financeiro> Mercado_Financeiro { get; set; }
        public virtual DbSet<Posicao> Posicao { get; set; }
        public virtual DbSet<Registo> Registo { get; set; }
        public virtual DbSet<Triplos> Triplos { get; set; }
        public virtual DbSet<Valores_Mercado> Valores_Mercado { get; set; }
        public virtual DbSet<resumo_portfolios> resumo_portfolios { get; set; }
    
        [DbFunction("PilimEntities", "listar_portfolio")]
        public virtual IQueryable<listar_portfolio_Result> listar_portfolio(string nomeP)
        {
            var nomePParameter = nomeP != null ?
                new ObjectParameter("nomeP", nomeP) :
                new ObjectParameter("nomeP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<listar_portfolio_Result>("[PilimEntities].[listar_portfolio](@nomeP)", nomePParameter);
        }
    
        public virtual int p_actualizaValorDiario()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_actualizaValorDiario");
        }
    }
}
