//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Si2_Fase2_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posicao
    {
        public string ISIN { get; set; }
        public string CC { get; set; }
        public Nullable<double> Quantidade { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Instrumento_Financeiro Instrumento_Financeiro { get; set; }
    }
}
