//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Si2_Fase2_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registo
    {
        public string ISIN { get; set; }
        public System.DateTime Dia { get; set; }
        public Nullable<decimal> ValorAbertura { get; set; }
        public Nullable<decimal> ValorFecho { get; set; }
        public Nullable<decimal> ValorMaximo { get; set; }
        public Nullable<decimal> ValorMinimo { get; set; }
        public Nullable<System.DateTime> HoraFecho { get; set; }
    
        public virtual Instrumento_Financeiro Instrumento_Financeiro { get; set; }
    }
}
