//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Si2_Fase2_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class resumo_portfolios
    {
        public string NomeCliente { get; set; }
        public string NomePortfolio { get; set; }
        public Nullable<int> NumeroIstrumentos { get; set; }
        public Nullable<decimal> ValorTotalPortfolio { get; set; }
    }
}
