//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Si2_Fase2_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Triplos
    {
        public string Identificacao { get; set; }
        public System.DateTime Dia { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<bool> Observado { get; set; }
    }
}
