//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Si2_Fase2_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Valores_Mercado
    {
        public System.DateTime Dia { get; set; }
        public string Codigo { get; set; }
        public Nullable<decimal> ValorIndice { get; set; }
        public Nullable<decimal> ValorAbertura { get; set; }
        public Nullable<decimal> VariacaoDiaria { get; set; }
    
        public virtual Mercado_Financeiro Mercado_Financeiro { get; set; }
    }
}
